[package]
name = "my_token_wallet_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.8.3"           # latest stable version (check for updates)
ic-cdk-macros = "0.4.0"
candid = "0.8.8"
serde = { version = "1.0", features = ["derive"] }
